# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vagrant.plugins = "vagrant-disksize"
  config.ssh.insert_key = false

  config.vm.box = "ubuntu/jammy64"
  
  config.vm.synced_folder '.', '/home/vagrant/compartido'
  config.vm.hostname = "1p2c-2024"
  config.vm.define :VM_1p2c_2024 do |t|
  end

  

  config.vm.network "private_network", :name => '', ip: "192.168.56.3"

  # Agrego  Discos Segun pdf del parcial.
  config.vm.disk :disk, size: "10GB", name: "extra_storage"
  config.vm.disk :disk, size: "2GB", name: "extra_storage2"


  config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = "1p2c-2024"
      vb.cpus = 2
      vb.linked_clone = true
  end

  # Puedo Ejecutar un script que esta en un archivo
  config.vm.provision "shell", path: "script_Enable_ssh_password.sh"


  config.vm.provision "shell", inline: <<-SHELL
    # Los comandos aca se ejecutan como root
    apt update && apt install -y tree
  SHELL
  
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    # Los comandos aca se ejecutan como vagrant
   
    # Puedo Generar una Nueva ssh-key de forma desatendida asi..
    ssh-keygen -t ed25519 -q -N "" -f "/home/vagrant/.ssh/id_ed25519"

    mkdir -p /home/vagrant/repogit
    cd /home/vagrant/repogit
    git clone https://github.com/upszot/UTN-FRA_SO_onBording.git 
    git clone https://github.com/upszot/UTN-FRA_SO_Examenes.git
    git clone https://github.com/upszot/UTN-FRA_SO_Guia_Ejercicios.git

  SHELL


  # Agrega la key Privada de ssh en .vagrant/machines/default/virtualbox/private_key
  config.ssh.insert_key = true

end
