# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Agrega la key Privada de ssh en .vagrant/machines/default/virtualbox/private_key
  config.ssh.insert_key = true
  
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.synced_folder '.', '/home/vagrant/compartido'
  config.vm.hostname = "1p2c-2024"
  config.vm.define :VM_1p2c_2024 do |t|
  end
  
  config.vm.network "private_network", :name => '', ip: "192.168.56.3"
  
  # Agrego  Discos Segun pdf del parcial.
  #config.vagrant.plugins = "vagrant-disksize"
  config.vm.disk :disk, size: "10GB", name: "extra_storage"
  config.vm.disk :disk, size: "2GB", name: "extra_storage2"


  config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = "1p2c-2024"
      vb.cpus = 2
      vb.linked_clone = true
  end

  # Puedo Ejecutar un script que esta en un archivo
  config.vm.provision "shell", path: "script_Enable_ssh_password.sh"


  config.vm.provision "shell", inline: <<-SHELL
    # Los comandos aca se ejecutan como root
    export DEBIAN_FRONTEND=noninteractive

    echo "Actualizo repositorio de paquetes e instalo tree"
    apt-get update > /dev/null
    apt-get install -y tree > /dev/null
  SHELL
  
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    # Los comandos aca se ejecutan como vagrant
   
    # Puedo Generar una Nueva ssh-key de forma desatendida asi..
    ssh-keygen -t ed25519 -q -N "" -f "/home/vagrant/.ssh/id_ed25519"

    mkdir -p /home/vagrant/repogit
    cd /home/vagrant/repogit
    git clone https://github.com/upszot/UTN-FRA_SO_onBording.git 
    git clone https://github.com/upszot/UTN-FRA_SO_Examenes.git
    git clone https://github.com/upszot/UTN-FRA_SO_Guia_Ejercicios.git

    # Genero carpeta simulando repositorio del Alumno
    mkdir -p $HOME/repogit/UTNFRA_SO_1P2C_2024_Resolucion
    cp -R $HOME/repogit/UTN-FRA_SO_Examenes/.git  $HOME/repogit/UTNFRA_SO_1P2C_2024_Resolucion/
    # Inicio Estructura de directorio del examen
    $HOME/repogit/UTN-FRA_SO_Examenes/202410/script_Precondicion.sh
    source ~/.bashrc  && history -a 
    
  SHELL

  # Mensaje post-up...
  config.vm.post_up_message = <<-MENSAJE
  
  ###########################################################################
  #
  # Este equipo esta preparado para Mostrar la Resolucion del Examen:
  #
  ###########################################################################
  # -- Si Usted desea realizar el mismo: 
  # 1. Elimine la siguiente carpeta (dentro de la VM)
  vagrant ssh
  rm -rf $HOME/repogit/UTNFRA_SO_1P2C_2024_Resolucion/
  
  # 2. Siga las Indicaciones del README.md y pdf del examen
  
  # -- Por el contrario si quiere recrear la resolucion del Examen
  # 1. Ejecute los scripts de resolucion dentro de:.
  
  /home/vagrant/repogit/UTN-FRA_SO_Examenes/202410/Resolucion/Script_1er2c_Parcial_2024_Practico/

  MENSAJE


end
