# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #config.vm.box = "generic/rhel7"
  #config.vm.box = "ubuntu/focal64"
  config.vm.box = "ubuntu/jammy64"

  config.vm.synced_folder '.', '/home/vagrant/foo'
  config.vm.hostname = "Examen202311"
  config.vm.define :Examen202311 do |t|
  end

  config.vm.network "private_network", :name => '', ip: "192.168.56.230"

  # Agrego un nuevo disco (Ver Readme.md)
  config.vm.disk :disk, size: "1GB", name: "extra_storage"
  config.vm.disk :disk, size: "3GB", name: "extra_storage2"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = "Examen202311"
      vb.cpus = 2
      vb.linked_clone = true
  end

  config.vm.provision "shell" do |shell|
    shell.path = "script_init.sh"
    shell.privileged = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Habilitamos acceso con clave por ssh
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    sudo systemctl restart sshd

    ls -l /home/vagrant/UTN-FRA_SO_Examenes
  SHELL

end
